<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <AssemblyName>jshepler.ngu.mods</AssemblyName>
        <Version>1.30.1</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>latest</LangVersion>
        <GameFolder>D:\Steam\steamapps\common\NGU IDLE</GameFolder>
        <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Plugin.cs" />
        <Compile Include="Options.cs" />
        <Compile Include="EnableVT.cs" />
        <Compile Include="Fonts.cs" />
        <Compile Include="Menu.cs" />
        <Compile Include="ClickHandlerComponent.cs" />
        <Compile Include="NumberFormating.cs" />
        <Compile Include="SimpleJSON.cs" />
        <Compile Include="SimpleJSONDotNetTypes.cs" />
        <Compile Include="IsExternalInit.cs" />
        <Compile Include="AutoHarvestFruits.cs" />
        <Compile Include="AutoDailyActions.cs" />
        <Compile Include="AutoBloodMagic.cs" />
        <Compile Include="ImprovedYggTooltips.cs" />
        <Compile Include="FixYggSeedsGainedDisplayFormat.cs" />
        <Compile Include="MergeBoostAll.cs" />
        <Compile Include="AutoTransformPendantsAndLooties.cs" />
        <Compile Include="Heirloom.cs" />
        <Compile Include="AutoManualMajorQuesting.cs" />
        <Compile Include="AutoButter.cs" />
        <Compile Include="AutoAdventure.cs" />
        <Compile Include="GameData\Fruits.cs" />
        <Compile Include="GameData\Quests.cs" />
        <Compile Include="ModSave\Data.cs" />
        <Compile Include="ModSave\LocalVar.cs" />
        <Compile Include="ModSave\ModPlayerData.cs" />
        <Compile Include="ModSave\Patches.cs" />
        <Compile Include="ModSave\PlayerDataBinder.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
        <PackageReference Include="BepInEx.Core" Version="5.*" />
        <PackageReference Include="BepInEx.PluginInfoProps" Version="1.*" />
        <PackageReference Include="UnityEngine.Modules" Version="2019.4.22" IncludeAssets="compile" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="$(GameFolder)\NGUIdle_Data\Managed\Assembly-CSharp.dll" />
        <Reference Include="$(GameFolder)\NGUIdle_Data\Managed\UnityEngine.UI.dll" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
    </ItemGroup>

    <Target Name="CopyDLL" AfterTargets="Build">
        <Copy SourceFiles="$(TargetDir)$(AssemblyName).dll" DestinationFolder="$(GameFolder)\BepInEx\plugins" />
    </Target>
</Project>
